pipeline {
    agent any

    stages {
        stage('Unit tests - backend') {
            agent {
                docker {
                    image 'snakee/golang-junit:1.21'
                    reuseNode true
                }
            }
            environment {
                HOME = '/tmp'
                GOCACHE = '/tmp/go-build'
                GOPATH = '/tmp/go'
                GOMODCACHE = '/tmp/go/pkg/mod'
            }
            steps {
                sh 'mkdir -p /tmp/go-build /tmp/go/pkg/mod'
                dir('bugtracker-backend') {
                    sh 'go test -v ./...'
                }
            }
        }
        stage('Unit tests - frontend') {
            agent {
                docker {
                    image 'node:18'
                    reuseNode true
                }
            }
            steps {
                dir('bugtracker-frontend') {
                    sh 'npm ci'
                    sh 'npm test'
                }
            }
    }
}
